### ISSUE TITLE
Wrong calculation is an order has several tax rates

### ISSUE THREAD

**Issue by handoyo** [abantecart/abantecart-src#397]
Hi admins, want to inform that recalc total on admin side is wrong when there are several tax rates within an order. Does abantecart only allow one tax rates assigned to an order? Thanks.

**Comment by abantecart** [comment]
Can you please provide more details what you do. How do you use recalc? Do you have screenshots?

**Comment by handoyo** [comment]
1. This is the unmodified order. 

![Unmodified](http://i575.photobucket.com/albums/ss197/yonghan79/not%20modified.jpg)

2. I update the product quantity and click the recalc button. Here is the results
![add product quantity](http://i575.photobucket.com/albums/ss197/yonghan79/recalc.jpg)

3. I removed the tax rates from the order:
![remove tax rate](http://i575.photobucket.com/albums/ss197/yonghan79/removed%20tax.jpg)

**Comment by BasaraABC** [comment]
In my opinion this section require a bit more development. Currently in allow only basic order edit, the cases like 2 taxes or other totals (coupons), totals from extensions may cause issues.

**Comment by abantecart** [comment]
This was fixed. 
This section is not very easy as we deal with many variables. 
I think we need to rethink how order is recalculated and if it is needed. Magento does not allow recalc and I see a reason for this. They offer to create a new/split order

Please give a second test to this.

**Comment by goatlady102** [comment]
Let me weigh in here  (this issue came up when we were making the Tax Reporting part of our Advanced Reports extension)  and yes it is not very easy.   But more importantly  I agree from an accounting audit standpoint that it would be preferable to not allow recalculation,  but to provide a way to create an amended order with line items for changes.     
Perhaps a same invoice number with an appended designation?  orig inv 1001 new amended - 1001-1 or 1001-A
And that becomes an entirely new replicated order that is changed in the same manner as an original one would be handled -  it would just need to carry over the payment what was made on the original order.  And adjust all the appropriate inventory adjustment.s

Lee

**Comment by abantecart** [comment]
Thank you for your comments Lee. We need to think more as this is complicated area and we want to make it simpler.

**Comment by abantecart** [comment]
In any who, it will be in 1.3 consideration.

**Comment by BasaraABC** [comment]
Still present bug with tax remove -  see screenshot
<img width="969" alt="2016-03-04_17-10-36" src="https://cloud.githubusercontent.com/assets/2631910/13524401/8e5a640c-e22d-11e5-93de-a431a9593334.png">

**Comment by abantecart** [comment]
2. On remove an non-confirm there is no change at all. There is no request sent, so values are not effected.
3. If tax is removed, second tax is re-calculated correctly any way on save and refresh. 

How did you get this? what browser?

**Comment by abantecart** [comment]
I see issue #2 now. Looking

**Comment by goatlady102** [comment]
If it helps you -  Handoyo handled the issue in our VatTax Id extension so that it works correctly when that extension is enabled.
He will be back at work in about 6 hrs  I can ask him to send you his solution.
Lee

**Comment by abantecart** [comment]
I was not able to find easy solution to this. This section is not my favorite. 
Tax key is shared and recalculation is not possible if deleted. 

**My solution it to prevent taxes or any duplicate total keys from deletion. ** Only update is possible. 

I think order recalculation section is requiring revisit in the future as I mentioned before.
